### PR TITLE
Support for Capstone 4.x

### LINKED ISSUE #3: Build Error trying to build Falcon example.
I am using Capstone 4.0.1-1 from Manjaro/Arch

Is this a version error?

```
  Compiling falcon_capstone v0.2.1
error[E0425]: cannot find value `cs_mode_CS_MODE_MIPSGP64` in this scope
  --> /home/externalreality/.cargo/registry/src/github.com-1ecc6299db9ec823/falcon_capstone-0.2.1/src/capstone_sys.rs:23:39
   |
23 | pub const CS_MODE_MIPSGP64: cs_mode = cs_mode_CS_MODE_MIPSGP64;
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `cs_mode_CS_MODE_MIPS64`

error[E0609]: no field `fp` on type `capstone_sys::cs_x86_op__bindgen_ty_1`
  --> /home/externalreality/.cargo/registry/src/github.com-1ecc6299db9ec823/falcon_capstone-0.2.1/src/capstone_sys.rs:38:47
   |
38 |         return unsafe { self.__bindgen_anon_1.fp };
   |                                               ^^ unknown field
   |
   = note: available fields are: `reg`, `imm`, `mem`, `_bindgen_union_align`

error[E0277]: the trait bound `capstone_sys::arm_reg: std::convert::From<i32>` is not satisfied
  --> /home/externalreality/.cargo/registry/src/github.com-1ecc6299db9ec823/falcon_capstone-0.2.1/src/capstone_sys.rs:75:51
   |
75 |         return unsafe { self.__bindgen_anon_1.reg.into() };
   |                                                   ^^^^ the trait `std::convert::From<i32>` is not implemented for `capstone_sys::arm_reg`
   |
   = help: the following implementations were found:
             <capstone_sys::arm_reg as std::convert::From<u32>>
   = note: required because of the requirements on the impl of `std::convert::Into<capstone_sys::arm_reg>` for `i32`

error[E0308]: mismatched types
   --> /home/externalreality/.cargo/registry/src/github.com-1ecc6299db9ec823/falcon_capstone-0.2.1/src/capstone_sys.rs:108:25
    |
108 |         return unsafe { self.__bindgen_anon_1.imm };
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected i32, found i64

error[E0308]: mismatched types
   --> /home/externalreality/.cargo/registry/src/github.com-1ecc6299db9ec823/falcon_capstone-0.2.1/src/capstone_sys.rs:123:25
    |
123 |         return unsafe { self.__bindgen_anon_1.imm };
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected i32, found i64

error: aborting due to 5 previous errors

Some errors occurred: E0277, E0308, E0425, E0609.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `falcon_capstone`.
```

### PR DESCRIPTION
**Pull request by wuggen**
Support is feature gated; `cargo build --features=capstone4` to enable.

Tested build with both Capstone 3.0.5 and 4.0.1, tested Falcon with the 3.0.5 build.

Fixes #3

### CODE REVIEW

**Comment by endeav0r** [comment]
I know originally I said I wasn't interested in 4.x capstone, but it looks like you've put a lot of work into this. If you want this merged to master, this is what I ask.

Work this simultaneously with a PR to falcon. The PR to falcon should reference your repository and branch for 4.x capstone directly. Once that PR for Falcon passes all of its tests (and you may need to update the docker, but keep it debian-based (Ubuntu or Debian are both find)), I will accept the PR here, then bump falcon and falcon_capstone simultaneously.

My main concern is this change breaking falcon.

**Comment by wuggen** [comment]
Are you thinking Capstone 4 in Falcon should be similarly feature gated, or just go ahead and make Capstone 4 the default?

**Comment by endeav0r** [comment]
You can go ahead and make capstone 4 the default, better than supporting two versions. The docker container will be the definitive environment, and should remain Debian based, and it should use capstone 4.

**Comment by wuggen** [comment]
Turns out capstone 4 isn't yet available from the Ubuntu or Debian package repos, which I didn't realize since I'm on Arch. I could go ahead with the change and just have the docker container fetch and build capstone 4 from source, or wait for capstone 4 to be available via apt-get, which might be a very long time. What do you think?

**Comment by endeav0r** [comment]
Wait for apt-get

**Comment by endeav0r** [comment]
Ok, I say we do this. Taking another look at this PR

**Comment by endeav0r** [comment]
We'll leave master with this PR for a bit, and once it seems gtg, we'll push a new crate, and then update falcon! :)
